### ISSUE TITLE
The format of TinyImageNet dataset

### ISSUE THREAD

**Issue by mengxujing** [lijiaqi/HALRP#1]
Hello, I encountered an issue while trying to reproduce your code, specifically related to the TinyImageNet dataset. The format of my dataset seems to be inconsistent with what your code is expecting. Would it be possible for you to share the format of the dataset as you processed it? Additionally, could you please let me know the size of the GPU memory used in your experiments?

**Comment by lijiaqi** [comment]
Hi,

Thanks for your interest in our work. I updated the repository by completing the scripts for downloading and preparing the datasets. See the README file for more details. 

As for your question about the GPU device, most of our experiments can be finished on the GPU with memory less than 12GB (the actual occupation can be much smaller). However, it may require larger memories on the TinyImageNet dataset.

Let me know if you have any further questions before I close this issue.

Best,

**Comment by mengxujing** [comment]
Hello ,
I've been struggling with an issue while replicating the Tiny dataset using a ResNet-18 backbone. Every time I train the base model and move on to task 2, calculating estimate_ranks causes a memory overflow. This happens specifically when executing u_dict[k], s_dict[k], v_dict[k] = torch.svd(discrepancy), regardless of whether I use a GPU with 24GB or 16GB of memory. I’m wondering if you've encountered this problem before and how you managed to resolve it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lijiaqi/HALRP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月1日(星期天) 凌晨0:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lijiaqi/HALRP] The format of TinyImageNet dataset (Issue #1)





 
Hi,
 
Thanks for your interest in our work. I updated the repository by completing the scripts for downloading and preparing the datasets. See the README file for more details.
 
As for your question about the GPU device, most of our experiments can be finished on the GPU with memory less than 12GB (the actual occupation can be much smaller). However, it may require larger memories on the TinyImageNet dataset.
 
Let me know if you have any further questions before I close this issue.
 
Best,

**Comment by lijiaqi** [comment]
Hi,

I saw you sent me an email about the questions for reproducing `ResNet18+TinyImageNet`. I cannot get your email address so I reopened this issue to answer your questions.

I just fixed some bugs that were introduced during our code cleaning. At least on my side, the experiments on TinyImageNet can be easily run with the command `bash scripts/tiny40_ResNet18_HALRP.sh`. As for your question about "memory overflow" when doing the SVD decomposition, I have to say that I didn't meet this issue. Could you please provide a short description about your environment that may help me reproduce it?

I can show you an example log file when I run the experiments on TinyImageNet datasets with ResNet18:
[tiny40_ResNet18_HALRP.log](https://github.com/user-attachments/files/16919274/tiny40_ResNet18_HALRP.log)

and a realtime GPU utility screenshot on my 4090 is as follows:
<img width="866" alt="Screenshot 2024-09-07 at 12 53 22" src="https://github.com/user-attachments/assets/21e4f3c6-2f56-47a2-9bd3-53b2f6cd25f9">

Let me know if you have any further questions.

**Comment by mengxujing** [comment]
Thank you very much for your response. I have resolved the issue with memory overflow. However, I couldn’t find the code related to the MODP and AODP metrics mentioned in your paper. Could you please point me to where it is? Thank you again for your help!

**Comment by lijiaqi** [comment]
The Order-normalized Performance Disparity (OPD) on a certain task $t$ is defined as the statistical range among the performances under $R$ different task orders (i.e., we take $R=5$ in our paper):

$$OPD_{t} = \max { P_{t}^{1}, \cdots, P_{t}^{R} } - \min { P_{t}^{1}, \cdots, P_{t}^{R} }$$

Then, AOPD and MOPD are calculated among all tasks according to the formulas in Section 5.3. The evaluation code should be easy to implement.

Best,

**Comment by mengxujing** [comment]
However, I encountered an issue when applying your method to my dataset, and I would greatly appreciate your assistance in optimizing the solution.

My dataset consists of large images (224x224), and while using your method, I experienced a memory overflow issue during the second task. Specifically, my device, an NVIDIA RTX 4090 with, ran out of memory.

I would be extremely grateful if you could help optimize the method to handle larger images more efficiently or provide any guidance on how to mitigate this memory issue.
